<a href="https://colab.research.google.com/github/beeguy74/PISCINE_PYTHON/blob/main/piscine_python_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercice 00: Give my BMI

In [ ]:
import numpy as np


def give_bmi(height: list[int | float], weight: list[int | float]) -> list[int | float]:
  '''take 2 lists of integers or floats in input and returns a list
      of BMI values. BMI = poids[kg] / taille2[m2]'''
  res = []
  try:
    res = np.divide(weight, np.square(height)).tolist()
  except Exception as e:
    print("Error give_bmi:",e)
  return res

def apply_limit(bmi: list[int | float], limit: int) -> list[bool]:
  '''accepts a list of integers or floats and an integer representing
    a limit as parameters. It returns a list of booleans
    (True if above the limit)'''
  res = []
  try:
    res = np.vectorize(lambda num: num > limit)(bmi).tolist()
  except Exception as e:
    print("Error apply_limit:", e)
  return res

def main():
# your tests and your error handling
  height = [2.71, 1.15]
  weight = [165.3, 38.4]
  bmi = give_bmi(height, weight)
  print(bmi, type(bmi))
  print(apply_limit(bmi, 26))

if __name__ == "__main__":
  main()

[22.507863455018317, 29.0359168241966] <class 'list'>
[False, True]


In [ ]:
#from give_bmi import give_bmi, apply_limit


height = [2.71, 1.15]
weight = [165.3, 38.4]
bmi = give_bmi(height, weight)
print(bmi, type(bmi))
print(apply_limit(bmi, 26))

[22.507863455018317, 29.0359168241966] <class 'list'>
[False, True]


Exercice 01: 2D array

In [ ]:
import numpy as np


def slice_me(family: list, start: int, end: int) -> list:
  ''' takes as parameters a 2D array, prints its shape, and returns a
truncated version of the array based on the provided start and end arguments.'''
  try:
    res = family[start:end]
    print("My shape is :", np.shape(family))
    print("My new shape is :", np.shape(res))
    return res
  except Exception as e:
    print("Error slice_me:",e)

def main():
  # your tests and your error handling
  family = [[1.80, 78.4],
            [2.15, 102.7],
            [2.10, 98.5],
            [1.88, 75.2]]
  print(slice_me(family, 0, 2))
  print(slice_me(family, 1, -2))

if __name__ == "__main__":
  main()

My shape is : (4, 2)
My new shape is : (2, 2)
[[1.8, 78.4], [2.15, 102.7]]
My shape is : (4, 2)
My new shape is : (1, 2)
[[2.15, 102.7]]


In [ ]:
#from array2D import slice_me

family = [[1.80, 78.4],
[2.15, 102.7],
[2.10, 98.5],
[1.88, 75.2]]
print(slice_me(family, 0, 2))
print(slice_me(family, 1, -2))

My shape is : (4, 2)
My new shape is : (2, 2)
[[1.8, 78.4], [2.15, 102.7]]
My shape is : (4, 2)
My new shape is : (1, 2)
[[2.15, 102.7]]


Exercice 02: load my image

In [24]:
import numpy as np
from PIL import Image


def ft_load(path: str) -> np.ndarray:
  ''' loads an image, prints its format, and its pixels
  content in RGB format.'''
  try:
    with Image.open(path) as f:
      data = np.array(f)
      print("The shape of image is: ", np.shape(data))
      return data
  except Exception as e:
    print("Error ft_load:",e)

def main():
  # your tests and your error handling
  print(ft_load("sample_data/landscape.jpeg"))
  print(ft_load("sample_data/README.md"))

if __name__ == "__main__":
  main()

The shape of image is:  (257, 450, 3)
[[[19 42 83]
  [23 42 84]
  [28 43 84]
  ...
  [69 42 51]
  [68 41 46]
  [68 41 46]]

 [[20 43 84]
  [24 43 85]
  [28 43 84]
  ...
  [71 44 53]
  [71 42 47]
  [71 42 47]]

 [[22 44 85]
  [25 44 84]
  [30 45 86]
  ...
  [74 44 54]
  [72 43 48]
  [72 43 48]]

 ...

 [[ 1  0  5]
  [ 1  0  5]
  [ 1  0  5]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 1  0  5]
  [ 1  0  5]
  [ 1  0  5]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  4]
  [ 0  0  4]
  [ 0  0  4]
  ...
  [ 0  0  0]
  [ 1  1  1]
  [ 1  1  1]]]
Error ft_load: cannot identify image file 'sample_data/README.md'
None
